### ISSUE TITLE
Extension vs built-in support for tasks

### ISSUE THREAD

**Issue by md2perpe** [stuartthomson/vscode-buttons#1]
Except for buttons, what does one gain compared to [tasks](https://code.visualstudio.com/docs/editor/tasks)?

**Comment by stuartthomson** [comment]
It's currently not possible to have more than one tasks.json file per workspace. This means that tasks must either all be shared by a team or ignored by source control. This extension allows you to share tasks with the team but also create ad hoc scripts for yourself.

**Comment by md2perpe** [comment]
A possibility to include one or more secondary tasks.json files into the primary one would solve that, wouldn't it?

Something like this:
```
{
    "tasks": [
        {
            ...
        }
    ],
    "include": [
        "team_tasks.json",
        "smart_tasks.json"
    ]
}
```

Then you could have team_tasks.json shared in the repository, and every developer can include that into his tasks.json.

**Comment by stuartthomson** [comment]
Yes it would, I actually tried to do that as the extension first but it proved harder to implement than I imagined so I switched to doing it this way.
