### ISSUE TITLE
No buttons visible in vscode running in Ubuntu

### ISSUE THREAD

**Issue by AbhishekTaparia** [stuartthomson/vscode-buttons#2]
![Screenshot from 2020-03-23 19-18-14](https://user-images.githubusercontent.com/29476541/77324057-38679800-6d3c-11ea-9e6c-d87cb1f84b76.png)

**Comment by stuartthomson** [comment]
Thanks for reporting this, @AbhishekTaparia! I'll take a look.

**Comment by mail2julian** [comment]
I also have the same issue

**Comment by stuartthomson** [comment]
@AbhishekTaparia @mail2julian 
I'm struggling to replicate this issue. I have created a ubuntu VM and everything seems to be working:
![image](https://user-images.githubusercontent.com/1838353/77679416-6e01c080-6f8a-11ea-9d08-8322ac149a90.png)

What version of ubuntu and vscode did you guys see this on?

**Comment by mail2julian** [comment]
Ubuntu 18.04.2 LTS
Visual Studio Code 1.43.1

**Comment by AbhishekTaparia** [comment]
Actually the problem for me was file hierarchy..I didn't add buttons.json file in main directory but a directory beneath it. Sorry to bug you..!!

**Comment by stuartthomson** [comment]
I'm going to be making an update which will allow you to place the buttons file in other places, that could perhaps help.
